import koffi from "koffi";
import path from "path";
import { getLibDir, getLibFunctions } from "./libUtils.js";
import { Gsdk } from "./interfaces.js";

const currentFile = __filename;
const currentDir = path.dirname(currentFile);
const libPath = path.resolve(currentDir, "..", getLibDir());
const lib = koffi.load(libPath);
const libFunctions: Gsdk = getLibFunctions(lib);

export const init = libFunctions.init;
export const initWithName = libFunctions.initWithName;
export const getConfigOptionNumber = libFunctions.getConfigOptionNumber;
export const getConfigOptionBool = libFunctions.getConfigOptionBool;
export const getConfigOptionColor = libFunctions.getConfigOptionColor;
export const getConfigOptionKeyInput = libFunctions.getConfigOptionKeyInput;
export const setTargetDevice = libFunctions.setTargetDevice;
export const getSdkVersion = libFunctions.getSdkVersion;
export const saveCurrentLighting = libFunctions.saveCurrentLighting;
export const setLighting = libFunctions.setLighting;
export const restoreLighting = libFunctions.restoreLighting;
export const flashLighting = libFunctions.flashLighting;
export const pulseLighting = libFunctions.pulseLighting;
export const stopEffects = libFunctions.stopEffects;
export const excludeKeysFromBitmap = libFunctions.excludeKeysFromBitmap;
export const setLightingFromBitmap = libFunctions.setLightingFromBitmap;
export const setLightingForKeyWithScanCode = libFunctions.setLightingForKeyWithScanCode;
export const setLightingForKeyWithHidCode = libFunctions.setLightingForKeyWithHidCode;
export const setLightingForKeyWithQuartzCode = libFunctions.setLightingForKeyWithQuartzCode;
export const setLightingForKeyWithKeyName = libFunctions.setLightingForKeyWithKeyName;
export const saveLightingForKey = libFunctions.saveLightingForKey;
export const restoreLightingForKey = libFunctions.restoreLightingForKey;
export const flashSingleKey = libFunctions.flashSingleKey;
export const pulseSingleKey = libFunctions.pulseSingleKey;
export const stopEffectsOnKey = libFunctions.stopEffectsOnKey;
export const setLightingForTargetZone = libFunctions.setLightingForTargetZone;
export const shutdown = libFunctions.shutdown;
export default libFunctions;
